### ISSUE TITLE
ITRANS to Tam and Tam ext for paLLi and v^eRRi

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#262]
Part of #246  

ITRANS paLLi to Tamil gives பலுʼ, instead it should have been பள்ளி
Also, v^eRRi transliterates to வெருʼ instead of வெற்றி.

Please implement this  FOR TAMIL & TAM EXT:

outputs of பள்ளி and வெற்றி to be paL_Li and v^eR_Ri.

Basically, if there is a vowel before the sequence RRi, RRI and LLi, LLI it becomes R_Ri/I and L_Li/I.

**Comment by virtualvinodh** [comment]
Fixed.

**Comment by nsesha92** [comment]
I think problem still persists.

--------------
Warm regards
Seshadri
