### ISSUE TITLE
Grantha Vl (LLi) CVC combo

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#263]
Similar to #246 

kLLi should be equal to കഌ, like ka = ക etc
but kaLLi is mapped to കഌ

same for kh, g, ... h

all pure consonants with vowel sign LLi , LLI combo.

![Grantha Vl (LLi) CVC combo #263](https://github.com/virtualvinodh/aksharamukha/assets/33624096/397ab344-44e8-4c18-8cdb-7bbd7ccad3cb)

**Comment by virtualvinodh** [comment]
Fixed.

**Comment by nsesha92** [comment]
i think still problem persists.
[kLLI error 263-262.pdf](https://github.com/user-attachments/files/16097609/kLLI.error.263-262.pdf)
